version: '3.8'
services:
  frontend:
    build: ./maps.frontend
    image: maps-frontend-dev
    container_name: maps-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"  # Порт для разработки
    volumes:
      - ./maps.frontend:/app  # Монтируем текущую директорию
      - /app/node_modules     # Исключаем node_modules из монтирования
    environment:
      - CHOKIDAR_USEPOLLING=true  # Для отслеживания изменений в Docker
    command: npm run dev  # Запуск dev-сервера
    networks:
      - maps-network

  backend:
    build: ./maps.backend
    image: maps-backend-dev
    container_name: maps-backend-dev
    restart: unless-stopped
    volumes:
      - ./maps.backend:/var/www/html
      - maps_backend:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=your_app_key_here
      - DB_CONNECTION=pgsql
      - DB_HOST=postgis_db
      - DB_PORT=5432
      - DB_DATABASE=your_db_name
      - DB_USERNAME=your_db_username
      - DB_PASSWORD=your_db_password
    depends_on:
      - geoserver
    networks:
      - maps-network
      - postgis-network

  geoserver:
    image: docker.osgeo.org/geoserver:2.26.2
    container_name: maps-geoserver-dev
    restart: unless-stopped
    volumes:
      - maps_geoserver:/opt/geoserver_data/
    environment:
      - INSTALL_EXTENSIONS=true
      - GEOSERVER_CSRF_DISABLED=true
      - GEOSERVER_CSRF_WHITELIST=betamaps.admsurgut.ru
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,HEAD,OPTIONS
      - CORS_ALLOWED_HEADERS=*
    networks:
      - maps-network
      - postgis-network

  nginx:
    image: nginx:stable-alpine
    container_name: maps-nginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf  # Конфиг для разработки
      - ./nginx/ssl:/etc/ssl
    command: nginx -g 'daemon off;'
    depends_on:
      - frontend
      - backend
    networks:
      - maps-network

volumes:
  maps_backend:
  maps_geoserver:

networks:
  maps-network:
    driver: bridge
    name: maps-network
  postgis-network:
    external: true
